# Generated by Django 5.1 on 2024-11-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
    ]
